export const products = [
  { id: 0, 
    name: 'น้องแมวขี้อ้อน', 
    price: 200, 
    imageId: 'MK3eW3A' },
  { id: 1, 
    name: 'น้องแมวนำโชค', 
    price: 150, 
    imageId: 'mynHUSa' },
  { id: 2, 
    name: 'น้องแมวขนปุ้ย', 
    price: 180, 
    imageId: 'bE7W1ji' },
  { id: 3, 
    name: 'น้องแมวทำมือ', 
    price: 220, 
    imageId: 'IOjWm71' },
  { id: 4, 
    name: 'น้อองแมวนุ่มนิ่ม', 
    price: 250, 
    imageId: 'lrWQx8l' },
  { id: 5, 
    name: 'น้องแมวในตะกร้า', 
    price: 300, 
    imageId: 'XY7eW2A' },
  { id: 6, 
    name: 'น้องแมวน่ากอด',
    price: 100, 
    imageId: 'UJ3nX8L' },
  { id: 7, 
    name: 'น้องแมววิบวับ', 
    price: 120, 
    imageId: 'PQ9kZ4B' },
  { id: 8, 
    name: 'น้องแมวน่ารัก', 
    price: 180, 
    imageId: 'QZ2jW5N' },
  { id: 9, 
    name: 'น้องแมวน่ายิ้ม', 
    price: 350, 
      imageId: 'BC8kW4P' }
];

// data.js
